spring:
  datasource:
    username: im_admin
    jdbc-url: jdbc:mysql://106.15.233.185:3306/lin_im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
