spring:
  datasource:
    username: xx
    jdbc-url: jdbc:mysql://xxx:3306/xxx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: xx
    driver-class-name:  com.mysql.cj.jdbc.Driver
